version: '3.4'

services:
  cadastrocurriculos:
    image: cadastrocurriculos
    build:
      context: Cadastro_Curriculos
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
